### PR TITLE
chore: Updating pre-commit config to run on modified files

### PR DESCRIPTION
**Pull request by manasaV3**
### Changes introduced: 
- Updates pre-commit to only run on files that have been updated.

### CODE REVIEW

**Comment by uermel** [comment]
Instead of fixing the linting of the `metadata_models.py` directly it would probably be better to fix the makefile. I had attempted to include linting in the build process here: https://github.com/chanzuckerberg/cryoet-data-portal-backend/blob/757fd3f791969babf8bf53e9ba917cc62cfe2072/schema/v1.1.0/Makefile#L14 , but I think this only does black linting and doesn't pass ruff. I'm not sure what the correct ruff command would be to fix it appropriately?

**Comment by manasaV3** [comment]
@uermel If the pre-commit is configured locally, it will run ruff, black, and the other hooks automatically before committing the changes. What are your thoughts on having the linting be a part of that instead of the build step?

**Comment by uermel** [comment]
> @uermel If the pre-commit is configured locally, it will run ruff, black, and the other hooks automatically before committing the changes. What are your thoughts on having the linting be a part of that instead of the build step?

Fine with me.  Sorry for not considering this should be its own package.

**Comment by manasaV3** [comment]
No worries! :)

**Review by jgadling — APPROVED** [review]

**Pull request merged**
